services:
  - type: web
    name: whatsapp-keyword-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: WHATSAPP_SESSION_PATH
        value: ./sessions
      - key: LOG_FILE
        value: ./logs/bot.log
    healthCheckPath: /health
    autoDeploy: true
    branch: main
